spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurantdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate      # Valida o schema em produção; para dev pode usar 'update' para aplicar alterações automáticas
    show-sql: true            # Mostrar SQL no console para debug
    properties:
      hibernate:
        format_sql: true      # Formatar SQL para melhor leitura
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:mysecretkey1234567890}   # Use variável ambiente JWT_SECRET para produção
  expiration: 86400000        # 1 dia em milissegundos

logging:
  level:
    org.springframework: INFO
    com.example.restaurant: DEBUG   # Log mais detalhado só para seu pacote

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
