spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurantdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate      # Valida o schema; use 'update' ou 'none' conforme necessidade
    show-sql: true            # Exibe as queries SQL no console
    properties:
      hibernate:
        format_sql: true      # Formata as queries SQL para melhor leitura
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true             # Ativa migrações automáticas via Flyway
    locations: classpath:db/migration  # Pasta com scripts de migração

server:
  port: 8080                  # Porta padrão do servidor Spring Boot

jwt:
  secret: ${JWT_SECRET:mysecretkey1234567890}   # Segredo JWT (prefira variável ambiente)
  expiration: 86400000        # Tempo de expiração do token em milissegundos (1 dia)

logging:
  level:
    org.springframework: INFO
    com.example.restaurant: DEBUG   # Log detalhado para seu pacote

springdoc:
  api-docs:
    path: /api-docs            # URL para JSON da API
  swagger-ui:
    path: /swagger-ui.html     # URL da interface Swagger UI
